### ISSUE TITLE
Can't install latest version 1.1.8

### ISSUE THREAD

**Issue by dabombUSA** [elkarte/Elkarte#3583]
Apache version 2.4.52
PHP version 8.1.2
MySQL version 8.0.28

Getting this error below on step 4 of installation.

Fatal error: Uncaught mysqli_sql_exception: Table 'elkarte.elkarte_settings' doesn't exist in C:\laragon\www\elkarte\sources\database\Db-mysql.class.php:261 Stack trace: #0 C:\laragon\www\elkarte\sources\database\Db-mysql.class.php(261): mysqli_query(Object(mysqli), '\n\t\t\tSELECT \n\t\t\t...') #1 C:\laragon\www\elkarte\install\Install_Controller.php(745): Database_MySQL->query('', '\n\t\t\tSELECT \n\t\t\t...', Array) #2 C:\laragon\www\elkarte\install\Install_Controller.php(55): Install_Controller->action_databasePopulation() #3 C:\laragon\www\elkarte\install\install.php(44): Install_Controller->dispatch(5) #4 {main} thrown in C:\laragon\www\elkarte\sources\database\Db-mysql.class.php on line 261

**Comment by Spuds** [comment]
Thank you for the report and details.   

This issue is most likely due to you running PHP 8.1.x which changed the way MySQLi generates errors.  Prior to 8.1 it would simply return false and perhaps generate  a warning.  Now it throws the exception you see.  Although the "error" is expected (in this case) but the way to handle it has changed.

Your first option is to use php 8.0.x as that is supported on that branch.  If that is not possible you will need to make a one line edit to the code to enable the pre 8.1 behavior for MySQLi, but do not there could be other issues with ElkArte 1.1.8 and PHP 8.1

**Comment by Spuds** [comment]
Fixed here: https://github.com/elkarte/Elkarte/pull/3646/commits/a59cdedaa36ab4fe1b4ad6a0fba6fae0316a7913
